theme: jekyll-theme-minimal
title: AVD Occasional
description: Cost-effective Azure Virtual Desktop for occasional users
show_downloads: true
github:
  repository_url: https://github.com/markheydon/avd-occasional
